# Generated by Django 4.2.6 on 2023-10-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.FileField(default='null', upload_to=''),
        ),
    ]
