# Generated by Django 4.2.6 on 2023-11-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_vaga_emprego_candidato_vaga_emprego'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
