# Generated by Django 4.2.6 on 2023-11-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0005_delete_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='valor',
            new_name='novo_valor',
        ),
        migrations.AddField(
            model_name='oferta',
            name='valor_antigo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
