# Generated by Django 4.2.6 on 2023-11-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_rename_valor_oferta_novo_valor_oferta_valor_antigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='imagem',
            field=models.ImageField(upload_to='static/ofertas/img'),
        ),
    ]
