# Generated by Django 4.2.6 on 2023-11-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0007_alter_oferta_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='oferta',
            name='imagem',
            field=models.ImageField(upload_to='media'),
        ),
    ]
