# Generated by Django 4.2.6 on 2023-11-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0008_usuario_alter_oferta_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='nome_usuario',
        ),
    ]
