# Generated by Django 4.2.6 on 2023-11-27 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0009_rename_nome_usuario_nome_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
