# Generated by Django 4.2.6 on 2023-12-10 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0010_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ofertas.categoria_oferta'),
        ),
    ]
